baseURL = '/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"



# add to "project_root/hugo.toml"
[markup]
  [markup.highlight]
    noClasses = false

# add to "project_root/hugo.toml"
disableKinds = ["taxonomy", "taxonomyTerm"]